USE [Test]
GO

/****** Object:  Index [ClIndex-NumOrder]    Script Date: 16.05.2020 18:23:14 ******/
CREATE UNIQUE CLUSTERED INDEX [ClIndex-NumOrder] ON [dbo].[TableOrder]
(
	[NumOrder] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [Test]
GO


/****** Object:  Index [NonClIndex-IDUserDateOfFormation]    Script Date: 16.05.2020 18:23:19 ******/
CREATE NONCLUSTERED INDEX [NonClIndex-IDUserDateOfFormation] ON [dbo].[TableOrder]
(
	[ID_USER] ASC,
	[DateOfFormation] ASC
)
INCLUDE([CostProduct]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO