USE [Test]
GO

/****** Object:  Index [ClIndex-ID_User]    Script Date: 16.05.2020 18:24:05 ******/
CREATE UNIQUE CLUSTERED INDEX [ClIndex-ID_User] ON [dbo].[Users]
(
	[ID_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


