USE [Test]
GO

/****** Object:  Index [ClIndex-ID]    Script Date: 16.05.2020 18:22:33 ******/
CREATE CLUSTERED INDEX [ClIndex-ID] ON [dbo].[Log_ActionUsers]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


